# Generated by Django 6.0.5 on 2026-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(default="Petrol", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(default="Automatic", max_length=50),
            preserve_default=False,
        ),
    ]
