# Generated by Django 6.0.5 on 2026-05-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_fuel_type_car_transmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
