# Generated by Django 6.0.5 on 2026-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_car_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hero_images/"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="hero_videos/"),
                ),
                (
                    "button_text",
                    models.CharField(default="Explore Cars", max_length=100),
                ),
                ("button_link", models.CharField(default="#cars", max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
